### ISSUE TITLE
License

### ISSUE THREAD

**Issue by msteinert** [krockot/gopam#1]
Hi, this repository has no license. Is that intentional?

**Comment by msteinert** [comment]
Hi, sorry for my previous terse comment. The reason why I ask is that I have made some [changes to the API](https://github.com/msteinert/pam) and I would like to use the code in a project, however the lack of license makes it [problematic to use](http://choosealicense.com/no-license/) in a commercial project.

I added the 2-clause BSD license (simplified version of the Golang license). I suspect you are very busy but if you could approve this license or propose a different one I would greatly appreciate it!

**Comment by trestletech** [comment]
Hi. We're blocked from being able to use this library without a license, as well. Any update would be much appreciated! Thanks.

**Comment by dakshinai** [comment]
Hi, 

We are interested in using this library for an opensource project. Could you confirm if the library is not copyrighted? And if so, could you release the License?

**Comment by msteinert** [comment]
At this point I would consider my fork a rewrite. Feel free to take a look.

https://github.com/msteinert/pam

**Comment by dakshinai** [comment]
Thank you. I'm unable to get transaction tests pass - TestPAM 1,2,3,4 and 6. I did create a test account as instructed in the README. Am I missing something. 

Could I open this as an issue in your repo?
